function SETUP = prepare_simulation(P,dt,totaltime,dx,L,saveInterval)
x = 0:dx:L;

sigma = CreateForcingStruct(0,0,totaltime,1,0);

BaseLevel = CreateForcingStruct(P.BL0,P.BLAmp,totaltime,P.BLPeriod,P.BLPhase);

Qw = CreateForcingStruct(P.Qw0,P.QwAmp,totaltime,P.QwPeriod,P.QwPhase);

Qsi0 = QsiFromSlope(P);
Qsi = CreateForcingStruct(Qsi0,P.QsiAmp,totaltime,P.QsiPeriod,P.QsiPhase);
% Qsi = CreateForcingStruct(P.Qsi0,P.QsiAmp,totaltime,P.QsiPeriod,P.QsiPhase);

eta0 = calculate_initial_elev(P,x,totaltime);
bf0 = calculate_flow_width(P,x,eta0,1,totaltime);
Bv0 = P.Bv*ones(1,length(bf0));

SETUP = struct(...
    'dt',dt,...
    'totaltime',totaltime,...
    'x',x,...
    'saveInterval',saveInterval,...
    'eta0',eta0,...
    'Bv0',Bv0,...
    'sigma',sigma,...
    'BaseLevel',BaseLevel,...
    'Qw',Qw,...
    'Qsi',Qsi...
    );

kmax = findMaxDiffusionCoeff(P,SETUP);
SETUP.dt = dx^2 / kmax * P.Bv/2;
