RESISTIVITY = struct(...
    'h',makedist('uniform','lower',8,'upper',24),...
    'R0_g',makedist('normal','mu',75,'sigma',12),...
    'R0_s',makedist('normal','mu',65,'sigma',12),...
    'R0_ms',makedist('normal','mu',25,'sigma',6),...
    'R0_m',makedist('normal','mu',13,'sigma',2.5),...
    'S_g', 0.2,...
    'S_s', 0.2,...
    'S_ms', 0.4,...
    'S_m', 0.4,...
    'Rt_g',makedist('normal','mu',0,'sigma',15),...
    'Rt_s',makedist('normal','mu',0,'sigma',12),...
    'Rt_ms',makedist('normal','mu',0,'sigma',9),...
    'Rt_m',makedist('normal','mu',0,'sigma',5) ...
    );