FRACTURE = struct(...
    'OutcropX', ,...
    'OutcropY', makedist,...
    'thx', makedist('uniform','lower',.5,'upper',100)... $m
    'strike', makedist('uniform','lower',0,'upper',360),... %degrees
    'dip', makedist('uniform','lower',0,'upper',90)... %degrees
    );
