RESISTIVITY = struct(...
    'h',makedist('uniform','lower',8,'upper',24),...
    'phi_g', makedist('uniform','lower',0.02,'upper',0.06),...
    'phi_s', makedist('uniform','lower',0,'upper',0.08),...
    'phi_ms', makedist('uniform','lower',0.1,'upper',0.2),...
    'phi_m', makedist('uniform','lower',0.3,'upper',0.7),...
    'Rw',makedist('lognormal','mu',log(7),'sigma',log(1.5)),...
    'Ra_g',makedist('normal','mu',105,'sigma',15),...
    'Ra_s',makedist('normal','mu',67,'sigma',12),...
    'Ra_ms',makedist('normal','mu',45,'sigma',9),...
    'Ra_m',makedist('normal','mu',20,'sigma',5) ...
    );