GEOMODEL = struct(...
    'St',4.8e-4,...
    'theta_s',makedist('uniform','lower',10,'upper',50),...
    'Sv',makedist('uniform','lower',9e-5,'upper',1.5e-3),...
    'Bv', makedist('uniform','lower',500,'upper',5000),...
    'Ss',makedist('uniform','lower',1,'upper',2)...
    );
