GEOMODEL = struct(...
    'Bv', makedist('uniform','lower',500,'upper',5000),...
    'Cf',makedist('uniform','lower',0.01,'upper',0.1),...
    'D',makedist('uniform','lower',0.001,'upper',0.05),...
    'g',9.8*(3600*24*365.25)^2,...
    'tau_star',makedist('uniform','lower',0.025,'upper',2.0),...
    'R',makedist('uniform','lower',1.75,'upper',2.0),...
    'Ss',makedist('uniform','lower',1,'upper',2),...
    'tau_star_c',makedist('uniform','lower',.047,'upper',.1),...
    'epsilon',makedist('uniform','lower',.6,'upper',.8),...
    'alpha',makedist('uniform','lower',1,'upper',3),...
    'sidewallFactor',0,...
    'Hv0',0.0001,...
    'Qw0',makedist('uniform','lower',4.4681e8,'upper',6.2553e10),...
    'QwAmp', makedist('uniform','lower',0,'upper',2e8),...
    'QwPeriod', .5,...
    'QwPhase', 0,...
    'Qsi0',2e5,...
    'QsiAmp', 0,...
    'QsiPeriod', .5,...
    'QsiPhase',0,...
    'BL0', 0,...
    'BLAmp', makedist('uniform','lower',-50,'upper',-30),...
    'BLPeriod', 0.5,...
    'BLPhase',0, ...
    'InitialSlope', 4.8e-4 ...
);
