OPENFAN = struct(...
    'fg',makedist('uniform','lower',0.01,'upper',0.10),...
    'fs',makedist('uniform','lower',0.25,'upper',0.5),...
    'fms',makedist('uniform','lower',0.20,'upper',0.30), ...
    'fm',-1,...
    'Lxg',makedist('uniform','lower',100,'upper',400), ...
    'Lxs',makedist('uniform','lower',500,'upper',800), ...
    'Lxms',makedist('uniform','lower',300,'upper',500),...
    'Lxm',0,...
    'Lyg',makedist('uniform','lower',500,'upper',800),...
    'Lys',makedist('uniform','lower',1250,'upper',1800),...
    'Lyms',makedist('uniform','lower',600,'upper',1000),...
    'Lym',0,...
    'Lzg',makedist('uniform','lower',1.5,'upper',3.0),...
    'Lzs',makedist('uniform','lower',3.0,'upper',5.0),...
    'Lzms',makedist('uniform','lower',1.0,'upper',2.0),...
    'Lzm',0,...
    'pxgs',makedist('uniform','lower',0.60,'upper',0.75),...
    'pxgms',makedist('uniform','lower',0.10,'upper',0.20),...
    'pxgm',0,...
    'pxsg',-1,...
    'pxsms',makedist('uniform','lower',0.31,'upper',0.48),...
    'pxsm',0,...
    'pxmsg',-1,...    
    'pxmss',-1,...
    'pxmsm',0,...
    'pxmg',0,...
    'pxms',0,...
    'pxmms',0,...
    'pygs',makedist('uniform','lower',0.60,'upper',0.75),...
    'pygms',makedist('uniform','lower',0.10,'upper',0.20),...
    'pygm',0,...
    'pysg',-1,...
    'pysms',makedist('uniform','lower',0.31,'upper',0.48),...
    'pysm',0,...
    'pymsg',-1,...    
    'pymss',-1,...
    'pymsm',0,...
    'pymg',0,...
    'pyms',0,...
    'pymms',0,...
    'pzgs',makedist('uniform','lower',0.95,'upper',0.99),...
    'pzgms',makedist('uniform','lower',0,'upper',0.02),...
    'pzgm',0,...
    'pzsg',makedist('uniform','lower',0.04,'upper',0.09),...
    'pzsms',makedist('uniform','lower',0.01,'upper',0.05),...
    'pzsm',0,...
    'pzmsg',makedist('uniform','lower',0.01,'upper',0.05),...    
    'pzmss',makedist('uniform','lower',0.10,'upper',0.25),...
    'pzmsm',0,...
    'pzmg',0,...
    'pzms',0,...
    'pzmms',0 ...
    );
IVF = struct(...
    'fg',makedist('uniform','lower',0.01,'upper',0.10),...
    'fs',makedist('uniform','lower',0.3,'upper',0.45),...
    'fms',makedist('uniform','lower',0.2,'upper',0.3), ...
    'fm',-1,...
    'Lxg',makedist('uniform','lower',100,'upper',400), ...
    'Lxs',makedist('uniform','lower',500,'upper',800), ...
    'Lxms',makedist('uniform','lower',300,'upper',500),...
    'Lxm',0,...
    'Lyg',makedist('uniform','lower',500,'upper',800),...
    'Lys',makedist('uniform','lower',1250 ,'upper', 1800),...
    'Lyms',makedist('uniform','lower',600,'upper',1000),...
    'Lym',0,...
    'Lzg',makedist('uniform','lower',1.5,'upper',3.0),...
    'Lzs',makedist('uniform','lower',3.0,'upper',5.0),...
    'Lzms',makedist('uniform','lower',1.0,'upper',2.0),...
    'Lzm',0,...
    'pxgs',makedist('uniform','lower',0.7,'upper',0.8),...
    'pxgms',makedist('uniform','lower',0.05,'upper',0.15),...
    'pxgm',0,...
    'pxsg',-1,...
    'pxsms',makedist('uniform','lower',0.50,'upper',0.60),...
    'pxsm',0,...
    'pxmsg',-1,...    
    'pxmss',-1,...
    'pxmsm',0,...
    'pxmg',0,...
    'pxms',0,...
    'pxmms',0,...
    'pygs',makedist('uniform','lower',0.70,'upper',0.85),...
    'pygms',makedist('uniform','lower',0.05,'upper',0.15),...
    'pygm',0,...
    'pysg',-1,...
    'pysms',makedist('uniform','lower',0.5,'upper',0.65),...
    'pysm',0,...
    'pymsg',-1,...    
    'pymss',-1,...
    'pymsm',0,...
    'pymg',0,...
    'pyms',0,...
    'pymms',0,...
    'pzgs',makedist('uniform','lower',0.95,'upper',0.99),...
    'pzgms',makedist('uniform','lower',0.01,'upper',0.05),...
    'pzgm',0,...
    'pzsg',makedist('uniform','lower',0.01,'upper',0.08),...
    'pzsms',makedist('uniform','lower',0.80,'upper',0.90),...
    'pzsm',0,...
    'pzmsg',makedist('uniform','lower',0.01,'upper',0.05),...    
    'pzmss',makedist('uniform','lower',0.10,'upper',0.20),...
    'pzmsm',0 ,...
    'pzmg',0 ,...
    'pzms',0 ,...
    'pzmms',0 ...
    );

COBBLES = struct(...
    'dc',makedist('uniform','lower',1,'upper',15),...
    'fg',makedist('uniform','lower',0.70,'upper',0.90),...
    'Lxg',makedist('uniform','lower',1000,'upper',3000),...
    'Lyg',makedist('uniform','lower',1500,'upper',5000),...
    'Lzg',makedist('uniform','lower',1.5,'upper',4.0)...
    );

% Could also add parameters like mean lengths and transition probs
